set(_AMENT_PACKAGE_NAME "kmc_hardware_driver_node")
set(kmc_hardware_driver_node_VERSION "1.0.0")
set(kmc_hardware_driver_node_MAINTAINER "Junggeun Seo <sjg12044@kaist.ac.kr>")
set(kmc_hardware_driver_node_BUILD_DEPENDS "rclcpp" "geometry_msgs" "std_msgs")
set(kmc_hardware_driver_node_BUILDTOOL_DEPENDS "ament_cmake")
set(kmc_hardware_driver_node_BUILD_EXPORT_DEPENDS "rclcpp" "geometry_msgs" "std_msgs")
set(kmc_hardware_driver_node_BUILDTOOL_EXPORT_DEPENDS )
set(kmc_hardware_driver_node_EXEC_DEPENDS "rclcpp" "geometry_msgs" "std_msgs")
set(kmc_hardware_driver_node_TEST_DEPENDS )
set(kmc_hardware_driver_node_GROUP_DEPENDS )
set(kmc_hardware_driver_node_MEMBER_OF_GROUPS )
set(kmc_hardware_driver_node_DEPRECATED "")
set(kmc_hardware_driver_node_EXPORT_TAGS)
list(APPEND kmc_hardware_driver_node_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
